spring:
  application:
    name: CardsGame
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

logging:
  level:
    web: debug
    org.springframework.web.socket: debug
